-- Script para eliminar todos los types definidos en siniestro_type_dependency.sql
-- El orden respeta las dependencias entre types (primero TABLE, luego OBJECT dependientes, luego OBJECT base)

DROP TYPE TAB_SBK_ANYDATA;

-- 1. Eliminar los TABLE types (colecciones)
DROP TYPE TAB_SBK_ENC_MENSAJE;
DROP TYPE TAB_SAP_DTMAPITEM;
DROP TYPE TAB_SAP_DATOS_RETENCIONES;
DROP TYPE TAB_SAP_DETALLES_CXP_SINI;
DROP TYPE TAB_SAP_DOCUMENTO_CXP_SINI;

-- 2. Eliminar los OBJECT más dependientes
DROP TYPE OBJ_SBK_MENSAJE;
DROP TYPE OBJ_SBK_MENSAJE_INF;
DROP TYPE OBJ_SBK_ENC_MENSAJE;
DROP TYPE OBJ_SAP_CXP_SINIESTROS;
DROP TYPE OBJ_SAP_CABECERA_CXP_SINI;
DROP TYPE OBJ_SAP_DOCUMENTO_CXP_SINI;
DROP TYPE OBJ_SAP_TERCERO;
DROP TYPE OBJ_SAP_DTMAP;
DROP TYPE OBJ_SAP_DTMAPITEM;
DROP TYPE OBJ_SAP_INFO_FISCAL;
DROP TYPE OBJ_SAP_DETALLE_CXP_SINI;
DROP TYPE OBJ_SAP_DATO_RETENCION;
DROP TYPE OBJ_SAP_CONDICION_PAGO_SINI;
DROP TYPE OBJ_SAP_CUENTA;
DROP TYPE OBJ_SAP_DATOS_CONVERSION;
