--5. add permissions to tables, types and packages to MAPEOINFO, OPS$ADM_ATRSURA, ADM_ATRSURA, OPS$SINI

-- ************ USER MAPEOINFO ************
--tables
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_1 TO MAPEOINFO;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_ERRORS_1 TO MAPEOINFO;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_HISTORY_1 TO MAPEOINFO;
--packages
GRANT EXECUTE ON OPS$PROCEDIM.pck_sin_adaptador_cpi TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.pck_cpi_integration_v2 TO MAPEOINFO;
--types
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_HEADERS TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_PARAM_ADICIONAL TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_PARAM_ADICIONAL TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CONTROL TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_DET_CONTABLE TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CAB_DATOS_GENERALES TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CABECERA TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_PARAM_CONTABLE TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DATOS_GENERALES TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DESCUENTO TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_RETENCION TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POS_RETENCION TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_GENERAL TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_PAGADOR TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_BANCARIO TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_DET_BANCARIA TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_RESUMEN TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DETALLE TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POS_DETALLE TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POSICION TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POSICION TO MAPEOINFO;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSACION_CONTABLE TO MAPEOINFO;

-- ************ USER OPS$ADM_ATRSURA ************
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_1 TO OPS$ADM_ATRSURA;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_ERRORS_1 TO OPS$ADM_ATRSURA;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_HISTORY_1 TO OPS$ADM_ATRSURA;
--packages
GRANT EXECUTE ON OPS$PROCEDIM.pck_sin_adaptador_cpi TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.pck_cpi_integration_v2 TO OPS$ADM_ATRSURA;
--types
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_HEADERS TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_PARAM_ADICIONAL TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_PARAM_ADICIONAL TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CONTROL TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_DET_CONTABLE TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CAB_DATOS_GENERALES TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CABECERA TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_PARAM_CONTABLE TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DATOS_GENERALES TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DESCUENTO TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_RETENCION TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POS_RETENCION TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_GENERAL TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_PAGADOR TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_BANCARIO TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_DET_BANCARIA TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_RESUMEN TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DETALLE TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POS_DETALLE TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POSICION TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POSICION TO OPS$ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSACION_CONTABLE TO OPS$ADM_ATRSURA;


-- ************ USER ADM_ATRSURA ************
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_1 TO ADM_ATRSURA;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_ERRORS_1 TO ADM_ATRSURA;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_HISTORY_1 TO ADM_ATRSURA;
--packages
GRANT EXECUTE ON OPS$PROCEDIM.pck_sin_adaptador_cpi TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.pck_cpi_integration_v2 TO ADM_ATRSURA;
--types
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_HEADERS TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_PARAM_ADICIONAL TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_PARAM_ADICIONAL TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CONTROL TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_DET_CONTABLE TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CAB_DATOS_GENERALES TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CABECERA TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_PARAM_CONTABLE TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DATOS_GENERALES TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DESCUENTO TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_RETENCION TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POS_RETENCION TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_GENERAL TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_PAGADOR TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_BANCARIO TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_DET_BANCARIA TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_RESUMEN TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DETALLE TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POS_DETALLE TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POSICION TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POSICION TO ADM_ATRSURA;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSACION_CONTABLE TO ADM_ATRSURA;


-- ************ USER OPS$SINI ************
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_1 TO OPS$SINI;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_ERRORS_1 TO OPS$SINI;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPS$PROCEDIM.TATR_ASYNC_TX_HISTORY_1 TO OPS$SINI;
--packages
GRANT EXECUTE ON OPS$PROCEDIM.pck_sin_adaptador_cpi TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.pck_cpi_integration_v2 TO OPS$SINI;
--types
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_HEADERS TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_PARAM_ADICIONAL TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_PARAM_ADICIONAL TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CONTROL TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_DET_CONTABLE TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CAB_DATOS_GENERALES TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_CABECERA TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_PARAM_CONTABLE TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DATOS_GENERALES TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DESCUENTO TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_RETENCION TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POS_RETENCION TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_GENERAL TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_PAGADOR TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_BANCARIO TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO_DET_BANCARIA TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_TERCERO TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_RESUMEN TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POS_DETALLE TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POS_DETALLE TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSA_POSICION TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.TAB_CPI_CAUSA_POSICION TO OPS$SINI;
GRANT EXECUTE ON OPS$PROCEDIM.OBJ_CPI_CAUSACION_CONTABLE TO OPS$SINI;